# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Pubudu Ranasinghe
tagline:          ''
description:      'Bits and Bytes'
url:              http://pubudu-ranasinghe.github.io/
baseurl:          '/'
paginate:         5

author:
  name:           'Pubudu Ranasinghe'
  url:            https://twitter.com/pubudutr

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/pubudu-ranasinghe/pubudu-ranasinghe.github.io
